orders = [
    {'id': 1,
     'product_name': 'Chic Dangle Earrings',
     'quantity': 2,
     'total_price': 100.00},
    {'id': 2,
     'product_name': 'Bohemian Layered Necklace',
     'quantity': 1,
     'total_price': 77.99},
    {'id': 3,
     'product_name': 'Elegant Rose Gold Ring',
     'quantity': 3,
     'total_price': 135.00},
    {'id': 4,
     'product_name': 'Charming Beaded Bracelet',
     'quantity': 4,
     'total_price': 320.00},
    {'id': 5,
     'product_name': 'Elegant Dress Watch',
     'quantity': 1,
     'total_price': 150.00},
]